// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"config-management-go/controller"
	"config-management-go/models/iteration"
	iteration2 "config-management-go/service/iteration"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func BuildApiInjector() (*ApiInjector, func(), error) {
	db, cleanup, err := InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	repository := iteration.NewRepository(db)
	service := iteration2.NewService(repository)
	iterationController := controller.NewIterationController(service)
	controllerInjector := NewControllerInjector(iterationController)
	engine := InitGinEngine(controllerInjector)
	apiInjector := NewApiInjector(engine)
	return apiInjector, func() {
		cleanup()
	}, nil
}
