// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"config-management-go/models/iteration"
)

// Injectors from wire.go:

func BuildApiInjector() (*ApiInjector, func(), error) {
	db, cleanup, err := InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	repository := iteration.NewRepository(db)
	engine := InitGinEngine(repository)
	apiInjector := NewApiInjector(engine)
	return apiInjector, func() {
		cleanup()
	}, nil
}
